title: Luis Enrique Pacheco Arana # your name (or website title) here
logo: "/images/img8x10.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Database developer & Data Specialist, CDMX, MÃ©xico
  <br><br>
  "Persistir por mis objetivos, trascender y dejar un legado de manera positiva 
  en mis colaboradores, amigos y familiares." 
  <br><br>
  
theme: jekyll-theme-minimal
